import 'dart:convert';

import 'package:convert/convert.dart';
import 'package:crypto/crypto.dart';
import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:http/http.dart' as http;

final apiServiceProvider = Provider(
  (ref) => ApiServiceProvider(),
);

class ApiServiceProvider {
  final String? podcastIndexApi = dotenv.env['PODCASTINDEX_API_KEY'];
  final String? podcastIndexSecret = dotenv.env['PODCASTINDEX_API_SECRET'];

  Future<Map<String, dynamic>> getPodcastsByFeedUrl(
      String podcastFeedUrl) async {
    var unixTime = (DateTime.now().millisecondsSinceEpoch / 1000).round();
    String newUnixTime = unixTime.toString();

    var firstChunk = utf8.encode(podcastIndexApi!);
    var secondChunk = utf8.encode(podcastIndexSecret!);
    var thirdChunk = utf8.encode(newUnixTime);

    var output = AccumulatorSink<Digest>();
    var input = sha1.startChunkedConversion(output);
    input.add(firstChunk);
    input.add(secondChunk);
    input.add(thirdChunk);
    input.close();
    var digest = output.events.single;

    Map<String, String> headers = {
      "X-Auth-Date": newUnixTime,
      "X-Auth-Key": podcastIndexApi!,
      "Authorization": digest.toString(),
      "User-Agent": "SomethingAwesome/1.0.1"
    };

    String cat = podcastFeedUrl.replaceAll(' ', '%20');

    String url =
        'https://api.podcastindex.org/api/1.0/episodes/byfeedurl?url=$cat&pretty';

    debugPrint(url);

    final response = await http.get(Uri.parse(url), headers: headers);

    if (response.statusCode == 200) {
      final String xmlString = response.body;
      return json.decode(xmlString);
    } else {
      throw Exception('Failed to get data from the API');
    }
  }

  // This method is used to get the list of podcasts from the API. Based on the category
  Future<Map<String, dynamic>> getPodcastsByCategory(String category) async {
    debugPrint(category);
    var unixTime = (DateTime.now().millisecondsSinceEpoch / 1000).round();
    String newUnixTime = unixTime.toString();

    var firstChunk = utf8.encode(podcastIndexApi!);
    var secondChunk = utf8.encode(podcastIndexSecret!);
    var thirdChunk = utf8.encode(newUnixTime);

    var output = AccumulatorSink<Digest>();
    var input = sha1.startChunkedConversion(output);
    input.add(firstChunk);
    input.add(secondChunk);
    input.add(thirdChunk);
    input.close();
    var digest = output.events.single;

    Map<String, String> headers = {
      "X-Auth-Date": newUnixTime,
      "X-Auth-Key": podcastIndexApi!,
      "Authorization": digest.toString(),
      "User-Agent": "SomethingAwesome/1.0.1"
    };

    String cat = category.replaceAll(' ', '%20');

    String url =
        'https://api.podcastindex.org/api/1.0/recent/feeds?cat=$cat&lang=en&pretty';

    debugPrint(url);

    final response = await http.get(Uri.parse(url), headers: headers);

    if (response.statusCode == 200) {
      final String xmlString = response.body;
      return json.decode(xmlString);
    } else {
      throw Exception('Failed to get data from the API');
    }
  }

  /// This method is used to get the list of podcasts from the API.
  ///
  /// The API uses a combination of the API key, secret key, and a Unix
  /// timestamp to generate a SHA1 hash. The hash is then used to authenticate
  /// the request.
  ///
  /// The API key is hard-coded in the app, and the secret key is stored in the
  /// [ApiKeys] class. The Unix timestamp is generated by the app when the
  /// request is made.
  ///
  /// The request is made to the API, and the response is parsed as JSON. The
  /// response is then returned as a [Map<String, dynamic>].
  Future<Map<String, dynamic>> getTrendingPodcasts() async {
    var unixTime = (DateTime.now().millisecondsSinceEpoch / 1000).round();
    String newUnixTime = unixTime.toString();

    var firstChunk = utf8.encode(podcastIndexApi!);
    var secondChunk = utf8.encode(podcastIndexSecret!);
    var thirdChunk = utf8.encode(newUnixTime);

    var output = AccumulatorSink<Digest>();
    var input = sha1.startChunkedConversion(output);
    input.add(firstChunk);
    input.add(secondChunk);
    input.add(thirdChunk);
    input.close();
    var digest = output.events.single;

    Map<String, String> headers = {
      "X-Auth-Date": newUnixTime,
      "X-Auth-Key": podcastIndexApi!,
      "Authorization": digest.toString(),
      "User-Agent": "SomethingAwesome/1.0.1"
    };

    String url =
        'https://api.podcastindex.org/api/1.0/podcasts/trending?max=150&lang=en&pretty';

    debugPrint(url);

    final response = await http.get(Uri.parse(url), headers: headers);

    if (response.statusCode == 200) {
      final String xmlString = response.body;
      return json.decode(xmlString);
    } else {
      throw Exception('Failed to get data from the API');
    }
  }

  Future<Map<String, dynamic>> getTopPodcasts() async {
    var unixTime = (DateTime.now().millisecondsSinceEpoch / 1000).round();
    String newUnixTime = unixTime.toString();

    var firstChunk = utf8.encode(podcastIndexApi!);
    var secondChunk = utf8.encode(podcastIndexSecret!);
    var thirdChunk = utf8.encode(newUnixTime);

    var output = AccumulatorSink<Digest>();
    var input = sha1.startChunkedConversion(output);
    input.add(firstChunk);
    input.add(secondChunk);
    input.add(thirdChunk);
    input.close();
    var digest = output.events.single;

    Map<String, String> headers = {
      "X-Auth-Date": newUnixTime,
      "X-Auth-Key": podcastIndexApi!,
      "Authorization": digest.toString(),
      "User-Agent": "SomethingAwesome/1.0.1"
    };

    final response = await http.get(
        Uri.parse(
          'https://api.podcastindex.org/api/1.0/recent/feeds?lang=en&pretty',
        ),
        headers: headers);

    if (response.statusCode == 200) {
      final String xmlString = response.body;
      return json.decode(xmlString);
    } else {
      throw Exception('Failed to get data from the API');
    }
  }

  Future<Map<String, dynamic>> getEducationPodcasts() async {
    var unixTime = (DateTime.now().millisecondsSinceEpoch / 1000).round();
    String newUnixTime = unixTime.toString();

    var firstChunk = utf8.encode(podcastIndexApi!);
    var secondChunk = utf8.encode(podcastIndexSecret!);
    var thirdChunk = utf8.encode(newUnixTime);

    var output = AccumulatorSink<Digest>();
    var input = sha1.startChunkedConversion(output);
    input.add(firstChunk);
    input.add(secondChunk);
    input.add(thirdChunk);
    input.close();
    var digest = output.events.single;

    Map<String, String> headers = {
      "X-Auth-Date": newUnixTime,
      "X-Auth-Key": podcastIndexApi!,
      "Authorization": digest.toString(),
      "User-Agent": "SomethingAwesome/1.0.1"
    };

    final response = await http.get(
        Uri.parse(
          'https://api.podcastindex.org/api/1.0/recent/feeds?max=3&cat=education&lang=en&pretty',
        ),
        headers: headers);

    if (response.statusCode == 200) {
      final String xmlString = response.body;
      return json.decode(xmlString);
    } else {
      throw Exception('Failed to get data from the API');
    }
  }

  Future<Map<String, dynamic>> getHealthPodcasts() async {
    var unixTime = (DateTime.now().millisecondsSinceEpoch / 1000).round();
    String newUnixTime = unixTime.toString();

    var firstChunk = utf8.encode(podcastIndexApi!);
    var secondChunk = utf8.encode(podcastIndexSecret!);
    var thirdChunk = utf8.encode(newUnixTime);

    var output = AccumulatorSink<Digest>();
    var input = sha1.startChunkedConversion(output);
    input.add(firstChunk);
    input.add(secondChunk);
    input.add(thirdChunk);
    input.close();
    var digest = output.events.single;

    Map<String, String> headers = {
      "X-Auth-Date": newUnixTime,
      "X-Auth-Key": podcastIndexApi!,
      "Authorization": digest.toString(),
      "User-Agent": "SomethingAwesome/1.0.1"
    };

    final response = await http.get(
        Uri.parse(
          'https://api.podcastindex.org/api/1.0/recent/feeds?max=3&cat=health&lang=en&pretty',
        ),
        headers: headers);

    if (response.statusCode == 200) {
      final String xmlString = response.body;
      return json.decode(xmlString);
    } else {
      throw Exception('Failed to get data from the API');
    }
  }

  Future<Map<String, dynamic>> getTechnologyPodcasts() async {
    var unixTime = (DateTime.now().millisecondsSinceEpoch / 1000).round();
    String newUnixTime = unixTime.toString();

    var firstChunk = utf8.encode(podcastIndexApi!);
    var secondChunk = utf8.encode(podcastIndexSecret!);
    var thirdChunk = utf8.encode(newUnixTime);

    var output = AccumulatorSink<Digest>();
    var input = sha1.startChunkedConversion(output);
    input.add(firstChunk);
    input.add(secondChunk);
    input.add(thirdChunk);
    input.close();
    var digest = output.events.single;

    Map<String, String> headers = {
      "X-Auth-Date": newUnixTime,
      "X-Auth-Key": podcastIndexApi!,
      "Authorization": digest.toString(),
      "User-Agent": "SomethingAwesome/1.0.1"
    };

    final response = await http.get(
        Uri.parse(
          'https://api.podcastindex.org/api/1.0/recent/feeds?max=3&cat=technology&lang=en&pretty',
        ),
        headers: headers);

    if (response.statusCode == 200) {
      final String xmlString = response.body;
      return json.decode(xmlString);
    } else {
      throw Exception('Failed to get data from the API');
    }
  }

  Future<Map<String, dynamic>> getSportsPodcasts() async {
    var unixTime = (DateTime.now().millisecondsSinceEpoch / 1000).round();
    String newUnixTime = unixTime.toString();

    var firstChunk = utf8.encode(podcastIndexApi!);
    var secondChunk = utf8.encode(podcastIndexSecret!);
    var thirdChunk = utf8.encode(newUnixTime);

    var output = AccumulatorSink<Digest>();
    var input = sha1.startChunkedConversion(output);
    input.add(firstChunk);
    input.add(secondChunk);
    input.add(thirdChunk);
    input.close();
    var digest = output.events.single;

    Map<String, String> headers = {
      "X-Auth-Date": newUnixTime,
      "X-Auth-Key": podcastIndexApi!,
      "Authorization": digest.toString(),
      "User-Agent": "SomethingAwesome/1.0.1"
    };

    final response = await http.get(
        Uri.parse(
          'https://api.podcastindex.org/api/1.0/recent/feeds?max=3&cat=sports&lang=en&pretty',
        ),
        headers: headers);

    if (response.statusCode == 200) {
      final String xmlString = response.body;
      return json.decode(xmlString);
    } else {
      throw Exception('Failed to get data from the API');
    }
  }
}
