import 'dart:convert';

import 'package:convert/convert.dart';
import 'package:crypto/crypto.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:http/http.dart' as http;
import 'package:openair/api_keys.dart';

final apiServiceProvider = Provider(
  (ref) => ApiServiceProvider(),
);

class ApiServiceProvider {
  /// This method is used to get the list of podcasts from the API.
  ///
  /// The API uses a combination of the API key, secret key, and a Unix
  /// timestamp to generate a SHA1 hash. The hash is then used to authenticate
  /// the request.
  ///
  /// The API key is hard-coded in the app, and the secret key is stored in the
  /// [ApiKeys] class. The Unix timestamp is generated by the app when the
  /// request is made.
  ///
  /// The request is made to the API, and the response is parsed as JSON. The
  /// response is then returned as a [Map<String, dynamic>].
  Future<Map<String, dynamic>> getPodcasts() async {
    var unixTime = (DateTime.now().millisecondsSinceEpoch / 1000).round();
    String newUnixTime = unixTime.toString();

    var firstChunk = utf8.encode(ApiKeys.apiKey);
    var secondChunk = utf8.encode(ApiKeys.apiSecret);
    var thirdChunk = utf8.encode(newUnixTime);

    var output = AccumulatorSink<Digest>();
    var input = sha1.startChunkedConversion(output);
    input.add(firstChunk);
    input.add(secondChunk);
    input.add(thirdChunk);
    input.close();
    var digest = output.events.single;

    Map<String, String> headers = {
      "X-Auth-Date": newUnixTime,
      "X-Auth-Key": ApiKeys.apiKey,
      "Authorization": digest.toString(),
      "User-Agent": "SomethingAwesome/1.0.1"
    };

    final response = await http.get(
        Uri.parse(
          'https://api.podcastindex.org/api/1.0/podcasts/trending?pretty&lang=en%2C+en-US',
        ),
        headers: headers);

    if (response.statusCode == 200) {
      final String xmlString = response.body;
      return json.decode(xmlString);
    } else {
      throw Exception('Failed to get data from the API');
    }
  }
}
