// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD67XpB9-kyBTSal2BgDotkQxiDqi69Lak',
    appId: '1:927721490543:web:fb060d091f2faf26cc259a',
    messagingSenderId: '927721490543',
    projectId: 'openair-27cb8',
    authDomain: 'openair-27cb8.firebaseapp.com',
    storageBucket: 'openair-27cb8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAszu2Dac5sSCDNlXPKcXY6u8xfC9AF9tA',
    appId: '1:927721490543:android:96365fd08c7b9810cc259a',
    messagingSenderId: '927721490543',
    projectId: 'openair-27cb8',
    storageBucket: 'openair-27cb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU0CgWQEYSebgTP79NrkBJ-rY_PS9TbQ8',
    appId: '1:927721490543:ios:f44b8b54ecc9fb74cc259a',
    messagingSenderId: '927721490543',
    projectId: 'openair-27cb8',
    storageBucket: 'openair-27cb8.firebasestorage.app',
    iosBundleId: 'com.example.openair',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU0CgWQEYSebgTP79NrkBJ-rY_PS9TbQ8',
    appId: '1:927721490543:ios:9ffed3aad9d12d1ecc259a',
    messagingSenderId: '927721490543',
    projectId: 'openair-27cb8',
    storageBucket: 'openair-27cb8.firebasestorage.app',
    iosBundleId: 'com.openair.podcast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD67XpB9-kyBTSal2BgDotkQxiDqi69Lak',
    appId: '1:927721490543:web:50ce2263c7ad9197cc259a',
    messagingSenderId: '927721490543',
    projectId: 'openair-27cb8',
    authDomain: 'openair-27cb8.firebaseapp.com',
    storageBucket: 'openair-27cb8.firebasestorage.app',
  );
}
