name: openair
title: OpenAir
version: 0.13.22
summary: A podcast manager for exploring and enjoying podcasts
description:
  OpenAir is a free and open-source cross-platform podcast app that empowers you to explore
  and enjoy the vast world of podcasts.
license: MIT
contact:
  - openairpodapp@gmail.com
donation:
  - https://www.paypal.com/donate/?hosted_button_id=F2UVR7PBQM5XQ
  - https://ko-fi.com/openairpodapp
issues: https://github.com/OpenAir-Podcast/OpenAir/issues
source-code: https://github.com/OpenAir-Podcast/OpenAir/
website: https://github.com/OpenAir-Podcast/OpenAir/

confinement: strict
base: core22
grade: stable
icon: snap/gui/icon.png

architectures:
  - build-on: amd64

slots:
  dbus-openair:
    interface: dbus
    bus: session
    name: org.openair.podcast

layout:
  /usr/lib/x86_64-linux-gnu/gstreamer-1.0:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/gstreamer-1.0
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /etc/ssl/certs:
    bind: $SNAP/etc/ssl/certs

apps:
  openair:
    command: OpenAir
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - browser-support
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - audio-playback
      - pulseaudio
      - home
      - removable-media
      - gsettings
      - unity7

    environment:
      # GStreamer configuration
      GST_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/x86_64-linux-gnu/gstreamer-1.0

      # SSL certificate paths
      SSL_CERT_DIR: $SNAP/etc/ssl/certs
      SSL_CERT_FILE: $SNAP/etc/ssl/certs/ca-certificates.crt

      # GDK settings
      GDK_BACKEND: x11

      # Flutter audio backend
      FLUTTER_TEST: "False"

    slots:
      - dbus-openair

parts:
  openair:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    flutter-channel: stable

    build-packages:
      - build-essential
      - cmake
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - liblzma-dev

      # GStreamer development
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-libav

      # Audio development
      - libpulse-dev
      - libasound2-dev

      # SSL/Networking
      - libssl-dev
      - libnss3-dev

    stage-packages:
      # Core system libraries
      - libc6
      - libgcc-s1
      - libstdc++6

      # SSL and certificates - CRITICAL FOR HTTPS
      - ca-certificates
      - openssl
      - libnss3
      - libnspr4

      # GStreamer core
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav

      # GStreamer HTTPS support - CRITICAL
      - gstreamer1.0-nice
      - gstreamer1.0-plugins-good

      # Audio support
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-alsa
      - libpulse0
      - libasound2
      - pulseaudio-utils

      # Additional codecs
      - gstreamer1.0-gl
      - gstreamer1.0-rtsp

      # Network support
      - gstreamer1.0-plugins-base-apps

      # GTK and desktop integration
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-0

    build-snaps: [flutter/latest/stable]
