name: openair
base: core22
version: '0.13.32'
title: OpenAir Podcast Player
summary: Free and open-source cross-platform podcast application
description: |
  OpenAir is a free and open-source podcast app built with Flutter, empowering 
  you to explore and enjoy the world of audio storytelling. Dive into a vast 
  library of podcasts, personalize your listening experience, and connect with 
  a vibrant community of fellow enthusiasts.
  
  Key Features:
  - Explore: Discover podcasts by category, popularity, and recommendations
  - Listen: Stream podcasts with offline listening capabilities
  - Organize: Create playlists, manage subscriptions, and track progress
  - Share: Recommend your favorite podcasts to friends

license: MIT
website: https://github.com/OpenAir-Podcast/OpenAir
source-code: https://github.com/OpenAir-Podcast/OpenAir
issues: https://github.com/OpenAir-Podcast/OpenAir/issues
donation: https://ko-fi.com/openairpodapp
contact: https://github.com/OpenAir-Podcast/OpenAir/discussions

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  openair:
    command: bin/OpenAir
    desktop: usr/share/applications/org.openair.podcast.desktop
    extensions: [gnome]
    environment:
      DISABLE_WAYLAND: 'true'
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
      GST_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner
      GST_DEBUG: "3"
    plugs:
      - home
      - network
      - network-bind
      - audio-playback
      - audio-record
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - opengl
      - gsettings
      - removable-media

parts:
  openair:
    plugin: flutter
    source: .
    flutter-channel: stable
    flutter-target: lib/main.dart
    
    build-packages:
      - clang
      - cmake
      - curl
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
      - libglu1-mesa
      - libmpv-dev
      - libsecret-1-dev
      - libjsoncpp-dev
      - libsqlite3-dev
      - pkg-config
      - libpulse-dev
      - libasound2-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-libav
      - gstreamer1.0-alsa
      - gstreamer1.0-pulseaudio
      - libblas-dev
      - liblapack-dev
    
    stage-packages:
      - libgtk-3-0
      - libglu1-mesa
      - libmpv1
      - libsecret-1-0
      - libjsoncpp25
      - libsqlite3-0
      - libpulse0
      - libayatana-appindicator3-1
      - libasound2
      - libasound2-plugins
      - alsa-utils
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-libav
      - gstreamer1.0-alsa
      - gstreamer1.0-pulseaudio
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libblas3
      - liblapack3
      - gstreamer1.0-plugins-ugly
      - libgfortran5
      - libquadmath0
      - gstreamer1.0-tools
    
    override-build: |
      craftctl default
      
      # Build the Flutter application for Linux
      flutter doctor -v
      flutter pub get
      flutter build linux --release --verbose
      
      # Copy built application to snap directory
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp -r build/linux/x64/release/bundle/* $CRAFT_PART_INSTALL/bin/
      
      # Make sure the main executable is actually executable
      chmod +x $CRAFT_PART_INSTALL/bin/OpenAir
  
  desktop-integration:
    plugin: dump
    source: snap/gui
    organize:
      org.openair.podcast.desktop: usr/share/applications/org.openair.podcast.desktop
      icon.png: usr/share/icons/hicolor/512x512/apps/openair.png
    stage-packages:
      - desktop-file-utils

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /etc/alsa:
    bind: $SNAP/etc/alsa
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0