name: openair
title: OpenAir
version: 0.13.2
summary: A podcast manager for exploring and enjoying podcasts
description:
  OpenAir is a free and open-source cross-platform podcast app that empowers you to explore
  and enjoy the vast world of podcasts.
license: MIT
contact:
  - openairpodapp@gmail.com
donation:
  - https://www.paypal.com/donate/?hosted_button_id=F2UVR7PBQM5XQ
  - https://ko-fi.com/openairpodapp
issues: https://github.com/OpenAir-Podcast/OpenAir/issues
source-code: https://github.com/OpenAir-Podcast/OpenAir/
website: https://github.com/OpenAir-Podcast/OpenAir/

confinement: strict
base: core22
grade: stable
icon: snap/gui/icon.png

slots:
  dbus-openair:
    interface: dbus
    bus: session
    name: org.openair.podcast

apps:
  openair:
    command: OpenAir
    extensions: [gnome]
    plugs:
      - network
      - desktop

parts:
  openair:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart