// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:openair/model/hive_models/completed_episode_model.dart';
import 'package:openair/model/hive_models/download_model.dart';
import 'package:openair/model/hive_models/episode_model.dart';
import 'package:openair/model/hive_models/feed_model.dart';
import 'package:openair/model/hive_models/fetch_data_model.dart';
import 'package:openair/model/hive_models/history_model.dart';
import 'package:openair/model/hive_models/podcast_model.dart';
import 'package:openair/model/hive_models/search_cache_model.dart';
import 'package:openair/model/hive_models/subscription_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CompletedEpisodeModelAdapter());
    registerAdapter(CompletedEpisodeModelAdapter());
    registerAdapter(DownloadModelAdapter());
    registerAdapter(DownloadModelAdapter());
    registerAdapter(EpisodeModelAdapter());
    registerAdapter(FeedModelAdapter());
    registerAdapter(FeedModelAdapter());
    registerAdapter(FetchDataModelAdapter());
    registerAdapter(FetchDataModelAdapter());
    registerAdapter(HistoryModelAdapter());
    registerAdapter(HistoryModelAdapter());
    registerAdapter(PodcastModelAdapter());
    registerAdapter(PodcastModelAdapter());
    registerAdapter(SearchCacheModelAdapter());
    registerAdapter(SearchCacheModelAdapter());
    registerAdapter(SubscriptionModelAdapter());
    registerAdapter(SubscriptionModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CompletedEpisodeModelAdapter());
    registerAdapter(CompletedEpisodeModelAdapter());
    registerAdapter(DownloadModelAdapter());
    registerAdapter(DownloadModelAdapter());
    registerAdapter(EpisodeModelAdapter());
    registerAdapter(FeedModelAdapter());
    registerAdapter(FeedModelAdapter());
    registerAdapter(FetchDataModelAdapter());
    registerAdapter(FetchDataModelAdapter());
    registerAdapter(HistoryModelAdapter());
    registerAdapter(HistoryModelAdapter());
    registerAdapter(PodcastModelAdapter());
    registerAdapter(PodcastModelAdapter());
    registerAdapter(SearchCacheModelAdapter());
    registerAdapter(SearchCacheModelAdapter());
    registerAdapter(SubscriptionModelAdapter());
    registerAdapter(SubscriptionModelAdapter());
  }
}
