// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:openair/models/completed_episode_model.dart';
import 'package:openair/models/download_model.dart';
import 'package:openair/models/episode_model.dart';
import 'package:openair/models/feed_model.dart';
import 'package:openair/models/fetch_data_model.dart';
import 'package:openair/models/history_model.dart';
import 'package:openair/models/podcast_model.dart';
import 'package:openair/models/queue_model.dart';
import 'package:openair/models/settings_model.dart';
import 'package:openair/models/subscription_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CompletedEpisodeModelAdapter());
    registerAdapter(CompletedEpisodeModelAdapter());
    registerAdapter(DownloadModelAdapter());
    registerAdapter(DownloadModelAdapter());
    registerAdapter(EpisodeModelAdapter());
    registerAdapter(EpisodeModelAdapter());
    registerAdapter(FeedModelAdapter());
    registerAdapter(FeedModelAdapter());
    registerAdapter(FetchDataModelAdapter());
    registerAdapter(FetchDataModelAdapter());
    registerAdapter(HistoryModelAdapter());
    registerAdapter(HistoryModelAdapter());
    registerAdapter(PodcastModelAdapter());
    registerAdapter(PodcastModelAdapter());
    registerAdapter(QueueModelAdapter());
    registerAdapter(QueueModelAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(SubscriptionModelAdapter());
    registerAdapter(SubscriptionModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CompletedEpisodeModelAdapter());
    registerAdapter(CompletedEpisodeModelAdapter());
    registerAdapter(DownloadModelAdapter());
    registerAdapter(DownloadModelAdapter());
    registerAdapter(EpisodeModelAdapter());
    registerAdapter(EpisodeModelAdapter());
    registerAdapter(FeedModelAdapter());
    registerAdapter(FeedModelAdapter());
    registerAdapter(FetchDataModelAdapter());
    registerAdapter(FetchDataModelAdapter());
    registerAdapter(HistoryModelAdapter());
    registerAdapter(HistoryModelAdapter());
    registerAdapter(PodcastModelAdapter());
    registerAdapter(PodcastModelAdapter());
    registerAdapter(QueueModelAdapter());
    registerAdapter(QueueModelAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(SubscriptionModelAdapter());
    registerAdapter(SubscriptionModelAdapter());
  }
}
