// Generated by Hive CE
// Do not modify
// Check in to version control

part of 'hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CompletedEpisodeModelAdapter());
    registerAdapter(CompletedEpisodeModelAdapter());
    registerAdapter(DownloadModelAdapter());
    registerAdapter(DownloadModelAdapter());
    registerAdapter(EpisodeModelAdapter());
    registerAdapter(EpisodeModelAdapter());
    registerAdapter(FeedModelAdapter());
    registerAdapter(FeedModelAdapter());
    registerAdapter(FetchDataModelAdapter());
    registerAdapter(HistoryModelAdapter());
    registerAdapter(HistoryModelAdapter());
    registerAdapter(PodcastModelAdapter());
    registerAdapter(PodcastModelAdapter());
    registerAdapter(QueueModelAdapter());
    registerAdapter(QueueModelAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(SubscriptionModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CompletedEpisodeModelAdapter());
    registerAdapter(CompletedEpisodeModelAdapter());
    registerAdapter(DownloadModelAdapter());
    registerAdapter(DownloadModelAdapter());
    registerAdapter(EpisodeModelAdapter());
    registerAdapter(EpisodeModelAdapter());
    registerAdapter(FeedModelAdapter());
    registerAdapter(FeedModelAdapter());
    registerAdapter(FetchDataModelAdapter());
    registerAdapter(HistoryModelAdapter());
    registerAdapter(HistoryModelAdapter());
    registerAdapter(PodcastModelAdapter());
    registerAdapter(PodcastModelAdapter());
    registerAdapter(QueueModelAdapter());
    registerAdapter(QueueModelAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(SubscriptionModelAdapter());
  }
}
