name: Play Store Release

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/openair-release.jks

      - name: Create key.properties
        run: echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - name: Build App Bundle
        run: flutter build appbundle --release --build-number=${{ github.run_number }}

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonKeyData: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
          packageName: com.liquidhive.openair
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
